export const siteConfig = {
  name: "Creamery Café",
  legalName: "Creamery The Classic Café",
  tagline: "The Gold Standard in Milkshakes • Peelamedu, Coimbatore",
  address: "124, Ram Lakshman Nagar, Peelamedu, Coimbatore, Tamil Nadu 641004",
  city: "Coimbatore",
  state: "Tamil Nadu",
  country: "India",
  postalCode: "641004",
  phone: import.meta.env?.VITE_CAFE_PHONE || "+91 98422 98765",
  whatsappNumber: import.meta.env?.VITE_WHATSAPP_NUMBER || "919842298765",
  instagram: "@creamery_cbe",
  instagramUrl: "https://www.instagram.com/creamery_cbe",
  googleMapsUrl: "https://share.google/ws5fVnMo9QNMw0CHS",
  openingHours: "11:00 AM – 11:30 PM (Mon - Sun)",
  rating: "4.9",
  reviewsTotal: "1,250+",
  staffPin: import.meta.env?.VITE_STAFF_PIN || "1234",
};
